GET http://localhost:5000/footballTeams

###

POST http://localhost:5000/footballCollection/new
Content-Type: application/json

{
    "team": "England",
    "gamesPlayed": 1,
    "wins": 1,
    "draw": 1,
    "loss": 1,
    "goalsFor": 1,
    "goalsAgainst": 1,
    "points": 1,
    "year": 1
}

###

DELETE http://localhost:5000/footballCollection/delete/65451a99c06033b4e768a0ae